% This script cleans the main directory incase someone built in the wrong
% spot. Be careful and make sure you don't need any files not in the list.

folder = [pwd '\'];
files = dir([folder '*.*']);
files = {files.name};

fileList = {...
    '.', ...
    '..', ...
    'build', ...
    'controllers', ...
    'Log Files', ...
    'clean.m', ...
    'atrias_system.slx', ...
    'startFcn.m',...
    'sys_params.m', ...
    'daq_params_cmu.m', ...
    'daq_params_osu.m', ...
    'set_sampletime.m', ...
    '7_medullas_4_elmos.xml', ...
    'instrument_panel.slrtip', ...
    'robotState_panel.slrtip', ...
    'temperature_panel.slrtip', ...
    'voltage_panel.slrtip', ...
    'testing_atrias.slx', ...
    'slrtnetboot.bat'};

deleteList = {};

% Construct list of files to delete
ind = ismember(files, fileList);
for i = 1:numel(ind)
    if ind(i) == 0
        deleteList{end+1} = files{i};
    end
end % for

% Display all files to be deleted
disp('FILES TO BE DELETED:');
for i = 1:numel(deleteList);
  disp([folder deleteList{i}])
end % for

% Prompt user to confirm they want to delete the listed files
answer = questdlg('Are you sure you want to delete all the listed files?');

% Loop through and delete files
if strcmp(answer, 'Yes')
    for i = 1:numel(deleteList);
       delete([folder deleteList{i}])
    end % for
end % if